name: expense_manager
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  fl_chart: ^0.70.1
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets: 
  - assets/home_logo.png
  - assets/enterntainment.png
  - assets/food.png
  - assets/fuel.png
  - assets/medicine.png
  - assets/shopping.png
  - assets/About us.png
  - assets/Category.png
  - assets/Graphs.png
  - assets/Transaction.png
  - assets/Trash.png
  - assets/imageHolder.png
