name: plants_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/plant.png
    - assets/plant2.png
    - assets/Group 5314(1).png
    - assets/circle1.png
    - assets/circle2.png
    - assets/plant3.png
    - assets/plant4.png
    - assets/shopping-bag.png
    - assets/shopping-bag-black.png
